### ISSUE TITLE
remove --prefer-dist from composer arguments

### ISSUE THREAD

**Issue by basz** [laminas/laminas-continuous-integration-action#126]
### Bug Report

Composer runs with unexpected default argument `--prefer-dist `.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.24.0

#### Summary

composer runs with `--prefer-dist`, which seems to be overriding configuration given in composer.json (preferred-install)

#### Current behavior

Composer seems to run with --prefer-dist as argument. This seems save as that is the stated default.

```
https://github.com/laminas/laminas-continuous-integration-action/blob/1.25.x/entrypoint.sh#L89
```

However adding this option will result in installing *all* packages with prefer source *even* if one configures via composer.json to prefer source for a specific package.

```
"config": {
        "preferred-install": {
            "my-org/*": "source"
        }
    }
```

#### How to reproduce

see https://github.com/basz/standard-projections/runs/8186520753 for an example of this.

Resulting in a missing test files from a different repo from the same org.

https://github.com/basz/standard-projections/runs/8186520753?check_suite_focus=true#step:3:457

A work-around is to add --prefer-source as additional argument which overrides `--prefer-dist`, but that becomes slow pretty.

#### Expected behavior

Composer should install with a minimum of assumptions and let end users choose additional arguments. I would expect --prefer-dist not be added as a default.

**Comment by Ocramius** [comment]
Perhaps you can drop it directly from https://github.com/laminas/laminas-continuous-integration-action/blob/6dcb42b5877523454d463bd6427aff3b92cfd192/entrypoint.sh#L89 ?

**Comment by basz** [comment]
what do you mean? 

> A work-around is to add --prefer-source as additional argument which overrides --prefer-dist, but that becomes slow pretty.

**Comment by Ocramius** [comment]
I just linked the line where `--prefer-dist` is specified: if you send a patch, it can be dropped :)

**Comment by Ocramius** [comment]
Handled in #127
