### ISSUE TITLE
Missing `make` command which was available in previous container versions

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-continuous-integration-action#135]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.16.0

#### Summary

With the optimization of this container, the `make` command started to be missing which was available previously. It was used by at least `laminas-cache-storage-adapter-apcu` to install the APCu extension from source and is primarily used by `pecl` to install PHP extensions.

#### Current behavior

`make: command not found`

#### How to reproduce

```
max@maxbookpro [~] 
→ docker run -it --entrypoint /bin/bash ghcr.io/laminas/laminas-continuous-integration:1.15 -c "make --version"
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
max@maxbookpro [~] 
→ docker run -it --entrypoint /bin/bash ghcr.io/laminas/laminas-continuous-integration:1.16 -c "make --version"
/bin/bash: make: command not found
```

#### Expected behavior

I'd expect make and stuff be available so that `pecl` can actually run OOTB without additional packages to be installed. I've thought that adding `php-pear` would be enough but it seems that it has no hard dependency on `make`.

```
max@maxbookpro [~] 
→ docker run -it --entrypoint /bin/bash ghcr.io/laminas/laminas-continuous-integration:1.15 -c "make --version"
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Ocramius** [comment]
Provided #138
