### ISSUE TITLE
Unable to locate package msodbcsql17

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-continuous-integration-action#159]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.33.x

#### Summary

When trying to build the container, I get the error mentioned in the title.

#### Current behavior

```
33.00 Reading package lists...
33.38 Building dependency tree...
33.46 Reading state information...
33.47 E: Unable to locate package msodbcsql17
```

The current builds seem to pass due to build caching. Not 100% sure about it as I am still very newbish when it comes to these kind of details.

Package seems to be available:

https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msodbcsql17/

#### How to reproduce

```
docker build . -t laminas/laminas-continuous-integration-action:latest
```

Ensure you have caches flushed.

#### Expected behavior

Build is passing.

**Comment by boesing** [comment]
Seems that `msodbcsql17` has been removed from or never been added to Ubuntu 22.04.
There is `msodbcsql18` available, is there a reason why we need `msodbcsql17` @weierophinney ?

**Comment by ghostwriter** [comment]
This was how I fixed this issue in my fork. I deleted the fork last week.

![image](https://github.com/laminas/laminas-continuous-integration-action/assets/9754361/9c6c32c3-e939-48d4-a227-1de50f02c608)

**Comment by boesing** [comment]
I tried that, doesn't seem to work (anymore).
No clue why this is a thing now, can install msodbcsql18 without issues (from the same source) but msodbsql17 seems to be gone.
No clue if that is considered as a BC break as I have no clue for what msodbsql17 is even used for...

ref: https://github.com/laminas/laminas-continuous-integration-action/pull/158/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R51-R53

**Comment by ghostwriter** [comment]
Versions 18, 17, 13.1, and 13 of the Linux and macOS drivers are supported on the x64 architecture of the following operating systems. The ARM64 architecture on macOS is supported starting with version 17.8. The ARM64 architecture on Red Hat 8, 9, Debian 11, and Ubuntu 20.04, 22.04 are supported starting with version 18.1.


References:

https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/system-requirements#operating-system-support

https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#18

https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#17

**Comment by ghostwriter** [comment]
I may be wrong, I believe it was initially installed to test `laminas-db` , but ultimately choose to use the docker "services" approach in GitHub actions.

**Comment by boesing** [comment]
Closing here for now as I cannot fully remember what I wanted to achieve with this issue.
Container builds and that should be good enough for now.
