### ISSUE TITLE
Syntax error with ini values in laminas-ci.json

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-continuous-integration-action#7]
I'm having some issues with adding ini values to `.laminas-ci.json` - I can't figure out why, but it appears that all the ini values are getting joined to a single line with spaces instead of a new line.

With some test json, running the below on my local machine does exactly what it's supposed to - each element is joined with \n as you'd expect, but still I have "Syntax error, unexpected =" when PHP parses the 99-settings.ini in CI.

https://github.com/laminas/laminas-continuous-integration-action/blob/92f18a56222df7f3d1896de178b6c0531c1af5a0/entrypoint.sh#L128

So far, I've tried 
- `cat path/to/99-settings.ini` to inspect the .ini file to verify the issue
- tried adding extra empty strings in the list of ini values ["foo=bar", "", "other=baz"]
- tried just a single ini setting  - ["foo=bar"]

I can see that the matrix action is sending sane JSON with a prepended `memory_limit=-1` and everything was working fine just a few day ago 🤷‍♂️

**Comment by weierophinney** [comment]
Can you link me to a job that displays the issue you're seeing, please?

**Comment by gsteel** [comment]
[This run](https://github.com/netglue/prismic-client/runs/2117250717?check_suite_focus=true#step:3:102) and it's associated [pull request](https://github.com/netglue/prismic-client/pull/21) has loads of commits with me fiddling around trying to get env vars passed through in order to upload coverage with codecov - You can see in that pull I'm dumping out the settings.ini in `post-run.sh` so you can also see it in the logs.

**Comment by weierophinney** [comment]
Okay, this was interesting to track down.

I normally use zsh. When I tried the jq command we use in the entrypoint to gather the INI values and separate them by newline, it works fine.

When I tried the same in bash... no newline.

Most likely it's a quoting issue; working on a fix now.
